import 'package:flutter/material.dart';

import './colorCode.dart';

final ccLight = new ColorCode(
  ccAppBarColor: Colors.white,
  ccPrimarySwatch: Colors.lightGreen,
  ccPrimaryColor: Colors.black,
  ccAppBarForegroundColor: Colors.deepOrangeAccent,
  ccBackgroundColor: Colors.white,
  ccGridColor1: Colors.amberAccent,
  ccGridColor2: Colors.indigoAccent,
  ccGridBorderColor1: Colors.amberAccent,
  ccGridBorderColor2: Colors.indigoAccent,
  ccGridTitleColor1: Colors.indigoAccent,
  ccGridTitleColor2: Colors.amberAccent,
  ccBatchDetailsForegroundColor: Colors.indigoAccent,
  ccMale: Colors.blue,
  ccFemale: Colors.pink,
  ccListTileTitle: Colors.black,
  ccListTileSubTitle: Colors.grey,
  ccListTileBackground: Colors.white,
  loadingBackground: Colors.white,
  loadingForeground: Colors.yellow,
  backgroundGradient1: Colors.lightGreen[300],
  backgroundGradient2: Colors.pink[200],
  mainBackgroundGradient1: Colors.pink,
  mainBackgroundGradient2: Colors.indigo,
  mainBackgroundGradient3: Colors.blue,
  quoteCardBorder: Colors.pink,
  editGradient1: Colors.lightGreen[300],
  editGradient2: Colors.pink[200],
  quoteCardText: Colors.black,
  ccBrightness: Brightness.light,
);

final ccDark = new ColorCode(
  ccAppBarColor: Colors.pink,
  ccPrimarySwatch: Colors.grey,
  ccPrimaryColor: Colors.white,
  ccAppBarForegroundColor: Colors.green,
  ccBackgroundColor: Colors.grey[850],
  ccGridColor1: Colors.black,
  ccGridColor2: Colors.black,
  ccGridBorderColor1: Colors.redAccent,
  ccGridBorderColor2: Colors.redAccent,
  ccGridTitleColor1: Colors.green,
  ccGridTitleColor2: Colors.green,
  ccBatchDetailsForegroundColor: Colors.green,
  ccMale: Colors.blue,
  ccFemale: Colors.pink,
  ccListTileTitle: Colors.green,
  ccListTileSubTitle: Colors.green,
  ccListTileBackground: Colors.black,
  loadingBackground: Colors.grey[850],
  loadingForeground: Colors.green,
  backgroundGradient1: Colors.black,
  backgroundGradient2: Colors.black,
  mainBackgroundGradient1: Colors.grey[850],
  mainBackgroundGradient2: Colors.grey[850],
  mainBackgroundGradient3: Colors.grey[850],
  quoteCardBorder: Colors.redAccent,
  editGradient1: Colors.grey[850],
  editGradient2: Colors.grey[850],
  quoteCardText: Colors.white,
  ccBrightness: Brightness.dark,
);
